server/src/main/java/challenge/server/auth/controller/AuthController.java
server/src/main/java/challenge/server/auth/dto/AuthDto.java
server/src/main/java/challenge/server/challenge/controller/ChallengeController.java
server/src/main/java/challenge/server/challenge/dto/ChallengeDto.java
server/src/main/java/challenge/server/review/controller/ReviewController.java
server/src/main/java/challenge/server/review/dto/ReviewDto.java

- 이미지 파일 관리 방법 정리 필요
Resolves: #19
어떤 변경 사항이 있나요?

feat - #19: API 통신을 위한 기본 Dto, Controller 구현(Challenge, Review, Auth)

---

server/src/main/java/challenge/server/category/controller/CategoryController.java
server/src/main/java/challenge/server/category/dto/CategoryDto.java
server/src/main/java/challenge/server/category/entity/Category.java
server/src/main/java/challenge/server/habit/controller/HabitController.java
server/src/main/java/challenge/server/habit/dto/HabitDto.java
server/src/main/java/challenge/server/habit/entity/Habit.java
server/src/main/java/challenge/server/report/controller/ReportController.java
server/src/main/java/challenge/server/report/dto/ReportDto.java
server/src/main/java/challenge/server/user/dto/UserDto.java
server/src/main/resources/application-local.yml

- Habit, Category, Report 도메인 Controller, DTO 구현
Related to: #18
어떤 변경 사항이 있나요?

feat - #18: API 통신을 위한 Controller, DTO 구현 (Habit, Category, Report)

---

server/src/main/java/challenge/server/category/controller/CategoryController.java
server/src/main/java/challenge/server/category/dto/CategoryDto.java
server/src/main/java/challenge/server/habit/controller/HabitController.java
server/src/main/java/challenge/server/habit/dto/HabitDto.java
server/src/main/java/challenge/server/habit/entity/Habit.java
server/src/main/java/challenge/server/report/controller/ReportController.java
server/src/main/java/challenge/server/report/dto/ReportDto.java
server/src/main/java/challenge/server/review/entity/Review.java
server/src/main/java/challenge/server/review/repository/ReviewRepository.java
server/src/main/java/challenge/server/review/service/ReviewService.java

- Post, PatchDTO 추가
- Swagger 애너테이션 적용
- Habit:Review = 1:N 매핑 수정
Related to: #18
어떤 변경 사항이 있나요?

feat - #18: API 통신를 위한 Controller, DTO 구현(Habit, Category, Report)

---

server/src/main/java/challenge/server/auth/dto/AuthDto.java
server/src/main/java/challenge/server/category/dto/CategoryDto.java
server/src/main/java/challenge/server/challenge/dto/ChallengeDto.java
server/src/main/java/challenge/server/habit/controller/HabitController.java
server/src/main/java/challenge/server/habit/dto/HabitDto.java
server/src/main/java/challenge/server/report/dto/ReportDto.java
server/src/main/java/challenge/server/review/dto/ReviewDto.java
server/src/main/java/challenge/server/security/dto/LoginDto.java
server/src/main/java/challenge/server/user/dto/UserDto.java
server/src/main/java/challenge/server/user/entity/User.java

- 회원 가입 시 Status 디폴트 값 설정 방식 수정(User 엔티티 수정)
- API 문서 애너테이션 추가(DTO 구분용)
어떤 변경 사항이 있나요?

fix - #11: User 엔티티 수정, docs - #20 #21 #22: API 문서 애너테이션 추가

---

server/src/test/java/challenge/server/challenge/repository/ChallnegeRepositoryTest.java
server/src/test/java/challenge/server/challenge/repository/WildcardRepositoryTest.java

fix: build를 위해 test 코드 주석 처리

---

server/src/test/java/challenge/server/challenge/repository/ChallnegeRepositoryTest.java
server/src/test/java/challenge/server/challenge/repository/WildcardRepositoryTest.java
server/src/test/resources/application.yml

fix: swagger 환경 설정 수정

---

server/src/main/java/challenge/server/category/controller/CategoryController.java
server/src/main/java/challenge/server/habit/controller/HabitController.java
server/src/main/java/challenge/server/report/controller/ReportController.java
server/src/main/java/challenge/server/report/dto/ReportDto.java

- 현재 존재하지 않는 엔드포인트 주석처리
- ReportDto 필드명 수정
- Habit Controller 북마크 삭제, 챌린지 상태변경 엔드포인트 추가
Related to: #18 
어떤 변경 사항이 있나요?

docs - #18: 현재 존재하지 않는 엔드포인트 주석처리

---

server/src/main/resources/application-local.yml
server/src/main/resources/application-server.yml

fix: 런타임 에러 해결

---

server/src/main/java/challenge/server/challenge/controller/ChallengeController.java
server/src/main/java/challenge/server/challenge/repository/ChallengeRepository.java
server/src/main/java/challenge/server/challenge/service/ChallengeService.java

- 특정 회원의 도전중인 모든 챌린지 조회 기능 추가
- 특정 회원이 완료한 모든 챌린지 조회 기능 추가
어떤 변경 사항이 있나요?

feat: API 통신을 위한 챌린지 조회 기능 추가

---

server/build.gradle
server/src/main/java/challenge/server/ServerApplication.java
server/src/main/java/challenge/server/auth/dto/AuthDto.java
server/src/main/java/challenge/server/auth/entity/Auth.java
server/src/main/java/challenge/server/challenge/controller/ChallengeController.java
server/src/main/java/challenge/server/exception/ExceptionCode.java
server/src/main/java/challenge/server/file/controller/FileUploadController.java
server/src/main/java/challenge/server/file/dto/FileDto.java
server/src/main/java/challenge/server/file/service/FileUploadService.java
server/src/main/java/challenge/server/file/storage/AmazonS3ResourceStorage.java
server/src/main/java/challenge/server/file/util/MultipartUtil.java
server/src/main/resources/application-local.yml
server/src/main/resources/application-server.yml
server/src/test/java/challenge/server/config/JasyptConfigTest.java
server/src/test/resources/application.yml

Related to: #124
어떤 변경 사항이 있나요?

feat - #124: Image 업로드 기능 구현

---

server/src/test/java/challenge/server/config/JasyptConfigTest.java

fix: JasypConfigTest 실패 해결

---

server/src/main/java/challenge/server/auth/service/AuthService.java
server/src/test/java/challenge/server/config/JasyptConfigTest.java

fix: File upload test를 위해 임시 주석 처리

---

server/src/main/java/challenge/server/audit/BaseTimeEntity.java
server/src/main/java/challenge/server/auth/service/AuthService.java
server/src/main/java/challenge/server/challenge/entity/Challenge.java
server/src/main/java/challenge/server/challenge/service/ChallengeService.java
server/src/test/java/challenge/server/auth/service/AuthServiceTest.java
server/src/test/java/challenge/server/challenge/service/ChallengeServiceTest.java

인증서 발급 방법에대해서 논의가 필요해보입니다.
어떤 변경 사항이 있나요?

feat: Challenge 성공 여부 자동 체크 기능 구현

---

server/src/main/java/challenge/server/challenge/service/ChallengeService.java
server/src/test/java/challenge/server/auth/service/AuthServiceTest.java
server/src/test/java/challenge/server/challenge/service/ChallengeServiceTest.java
server/src/test/resources/application.yml

successCheck 메서드 추가로 인해 발생한 NullpointerException을 해결하였습니다.
어떤 변경 사항이 있나요?

fix: NullPointerException 해결

---

server/src/main/java/challenge/server/category/dto/CategoryDto.java
server/src/main/java/challenge/server/category/entity/Category.java
server/src/main/java/challenge/server/category/mapper/CategoryMapper.java
server/src/main/java/challenge/server/category/repository/CategoryRepository.java
server/src/main/java/challenge/server/category/service/CategoryService.java
server/src/main/java/challenge/server/exception/ExceptionCode.java
server/src/main/java/challenge/server/habit/mapper/HabitMapper.java
server/src/main/java/challenge/server/habit/repository/HabitRepository.java
server/src/main/java/challenge/server/habit/service/HabitService.java
server/src/test/java/challenge/server/habit/HabitRepositoryTest.java

- Habit Service, Repository 구현
- Habit Controller Image 기능 범위 내 구현
Resolves: #24 #27
어떤 변경 사항이 있나요?

feat - #24 #27: Habit Image 업로드 기능 구현

---

server/src/main/java/challenge/server/user/service/UserService.java

fix: NullpointException 해결

---

.gitignore
server/build.gradle
server/src/main/java/challenge/server/challenge/repository/ChallengeCustomRepositoryImpl.java
server/src/main/java/challenge/server/config/SecurityConfig.java
server/src/main/java/challenge/server/security/dto/LoginDto.java
server/src/main/java/challenge/server/security/filter/JwtAuthenticationFilter.java
server/src/main/java/challenge/server/security/oauth/dto/OAuthAttributes.java
server/src/main/java/challenge/server/security/oauth/dto/SessionUser.java
server/src/main/java/challenge/server/security/oauth/handler/OAuth2MemberSuccessHandler.java
server/src/main/java/challenge/server/security/oauth/service/CustomOAuth2UserService.java
server/src/main/java/challenge/server/user/entity/User.java
server/src/main/resources/application-server.yml

- 로그인 진행 시 DB에 저장되는 것까지 확인하였고 JWT토큰 전달되는지 프론트엔드와 테스트해보아야 합니다.
Resolves: #12
어떤 변경 사항이 있나요?

feat - #12: OAuth2 로그인 구현(Google, Naver, Kakao)

---

server/src/main/java/challenge/server/security/oauth/dto/SessionUser.java
server/src/main/java/challenge/server/security/oauth/handler/OAuth2MemberSuccessHandler.java
server/src/main/resources/application-server.yml

feat: OAuth2 redirect-uri 수정

---

server/src/main/resources/application-server.yml

feat: redirect-uri 수정

---

server/src/main/java/challenge/server/auth/dto/AuthDto.java
server/src/main/java/challenge/server/auth/mapper/AuthMapper.java
server/src/main/java/challenge/server/habit/controller/HabitController.java
server/src/main/java/challenge/server/habit/dto/HabitDto.java
server/src/main/java/challenge/server/habit/mapper/HabitMapperImpl.java
server/src/main/java/challenge/server/review/dto/ReviewDto.java
server/src/main/java/challenge/server/review/mapper/ReviewMapper.java

- Habit Patch 핸들러 메서드 userId 파라미터 삭제
- 각 도메인 DTO username 필드 추가
Related to: #30
어떤 변경 사항이 있나요?

fix - #30: Habit Patch userId 파라미터 삭제, DTO username 필드 추가

---

server/src/main/java/challenge/server/auth/repository/AuthCustomRepository.java
server/src/main/java/challenge/server/auth/repository/AuthCustomRepositoryImpl.java
server/src/main/java/challenge/server/auth/repository/AuthRepository.java
server/src/main/java/challenge/server/auth/service/AuthService.java
server/src/main/java/challenge/server/bookmark/repository/BookmarkCustomRepository.java
server/src/main/java/challenge/server/bookmark/repository/BookmarkCustomRepositoryImpl.java
server/src/main/java/challenge/server/bookmark/repository/BookmarkRepository.java
server/src/main/java/challenge/server/bookmark/service/BookmarkService.java
server/src/main/java/challenge/server/challenge/controller/ChallengeController.java
server/src/main/java/challenge/server/challenge/dto/ChallengeDto.java
server/src/main/java/challenge/server/challenge/repository/ChallengeCustomRepositoryImpl.java
server/src/main/java/challenge/server/challenge/service/ChallengeService.java
server/src/main/java/challenge/server/habit/controller/HabitController.java
server/src/main/java/challenge/server/habit/repository/HabitCustomRepository.java
server/src/main/java/challenge/server/habit/repository/HabitCustomRepositoryImpl.java
server/src/main/java/challenge/server/habit/repository/HabitRepository.java
server/src/main/java/challenge/server/habit/service/HabitService.java
server/src/main/java/challenge/server/review/repository/ReviewCustomRepository.java
server/src/main/java/challenge/server/review/repository/ReviewCustomRepositoryImpl.java
server/src/main/java/challenge/server/review/repository/ReviewRepository.java
server/src/main/java/challenge/server/review/service/ReviewService.java
server/src/main/java/challenge/server/user/controller/UserController.java
server/src/main/java/challenge/server/user/mapper/UserMapperImpl.java
server/src/main/java/challenge/server/user/service/UserService.java
server/src/main/resources/db/h2/data.sql

- No-Offset 페이지네이션을 구현했지만 기존 Offset 페이지네이션을 사용할 수 있도록 설정해놨습니다. 추후 프론트엔드에서 작업 가능하게되면 쉽게 수정할 수 있도록 해놨습니다.
Related to: #191
어떤 변경 사항이 있나요?

feat - #191: No-Offset 페이지네이션 구현

---

server/src/main/java/challenge/server/security/oauth/handler/OAuth2MemberSuccessHandler.java

Related to: #12
어떤 변경 사항이 있나요?

feat - #12: OAuth2 프론트엔드로 넘기는 redirect url 변경

---

server/build.gradle
server/src/main/java/challenge/server/config/EmailConfig.java
server/src/main/java/challenge/server/config/WebMvcConfig.java
server/src/main/java/challenge/server/helper/email/EmailSendable.java
server/src/main/java/challenge/server/helper/email/SimpleEmailSendable.java
server/src/main/java/challenge/server/user/controller/UserController.java
server/src/main/java/challenge/server/user/dto/EmailVerificationDto.java
server/src/main/java/challenge/server/user/entity/EmailVerification.java
server/src/main/java/challenge/server/user/entity/User.java
server/src/main/java/challenge/server/user/repository/EmailVerificationCustomRepository.java
server/src/main/java/challenge/server/user/repository/EmailVerificationCustomRepositoryImpl.java
server/src/main/java/challenge/server/user/repository/EmailVerificationRepository.java
server/src/main/java/challenge/server/user/service/EmailService.java
server/src/main/java/challenge/server/user/service/UserService.java
server/src/main/resources/application-server.yml

- JWT refresh token 관련 CORS 설정 추가(header에 보이게 설정)
- 회원 가입 시 이메일 인증 관련 기능 구현 추가
어떤 변경 사항이 있나요?

fix - #11: JWT refresh token 관련 CORS 설정 추가

---

server/src/main/java/challenge/server/user/service/UserService.java

- 회원 가입 이메일 전송 관련 UserService 클래스 컴파일 오류 수정
Related to: #32 
어떤 변경 사항이 있나요?

fix - #32: 컴파일 오류 해결

---

server/src/main/java/challenge/server/user/service/UserService.java

- 회원 가입 전 이메일 인증 기능 주석 처리
Related to: #32
어떤 변경 사항이 있나요?

fix - #32: 회원 가입 전 이메일 인증 기능 주석 처리

---

server/src/main/java/challenge/server/auth/dto/AuthDto.java
server/src/main/java/challenge/server/auth/mapper/AuthMapper.java

feat: Auth Response 데이터(habitId) 추가

---

server/src/main/resources/application-server.yml

fix: MaxUploadSizeExceededException 해결

---

server/src/main/java/challenge/server/challenge/repository/ChallengeCustomRepositoryImpl.java
server/src/main/java/challenge/server/challenge/service/ChallengeService.java
server/src/main/java/challenge/server/habit/controller/HabitController.java
server/src/main/java/challenge/server/habit/entity/Habit.java
server/src/main/java/challenge/server/habit/mapper/HabitMapperImpl.java
server/src/main/java/challenge/server/habit/repository/HabitCustomRepository.java
server/src/main/java/challenge/server/habit/repository/HabitCustomRepositoryImpl.java
server/src/main/java/challenge/server/habit/service/HabitService.java

- 인기순, 최신순 습관 정렬 기능 추가
어떤 변경 사항이 있나요?

feat: 습관 정렬(인기순, 최신순) 기능 추가

---

server/src/main/resources/application-server.yml

docs: habit, users, challenge, auth 더미데이터 추가

---

server/src/main/resources/application-server.yml

docs: CommunicationsException 해결

---

server/src/main/resources/application-server.yml

docs: datasource url 수정

---

server/src/main/resources/application-server.yml

fix: UnknownHostException 해결

---

server/src/main/resources/application-server.yml

fix: UnknownHostsException 해결

---

server/src/main/resources/application-server.yml

fix: SqlExceptionHelper 해결

---

server/src/main/java/challenge/server/auth/repository/AuthCustomRepository.java
server/src/main/java/challenge/server/auth/repository/AuthCustomRepositoryImpl.java
server/src/main/java/challenge/server/auth/service/AuthService.java
server/src/main/java/challenge/server/habit/controller/HabitController.java
server/src/main/resources/application-server.yml

docs: review 더미데이터 추가

---

server/src/main/java/challenge/server/habit/dto/HabitDto.java
server/src/main/java/challenge/server/habit/entity/Habit.java
server/src/main/java/challenge/server/habit/mapper/HabitMapperImpl.java
server/src/main/java/challenge/server/report/dto/ReportDto.java
server/src/main/java/challenge/server/report/entity/Report.java

- Habit DTO, Entity mdBody 필드 추가
- Report Entity Enum 수정 및 추가
Related to: #30
어떤 변경 사항이 있나요?

feat - #30: Report Entity, Habit DTO 및 Mapper 수정

---

server/src/main/java/challenge/server/auth/repository/AuthCustomRepository.java
server/src/main/java/challenge/server/auth/repository/AuthCustomRepositoryImpl.java
server/src/main/java/challenge/server/auth/service/AuthService.java
server/src/main/java/challenge/server/bookmark/repository/BookmarkCustomRepository.java
server/src/main/java/challenge/server/bookmark/repository/BookmarkCustomRepositoryImpl.java
server/src/main/java/challenge/server/bookmark/service/BookmarkService.java
server/src/main/java/challenge/server/challenge/controller/ChallengeController.java
server/src/main/java/challenge/server/challenge/repository/ChallengeCustomRepository.java
server/src/main/java/challenge/server/challenge/repository/ChallengeCustomRepositoryImpl.java
server/src/main/java/challenge/server/challenge/repository/ChallengeRepository.java
server/src/main/java/challenge/server/challenge/service/ChallengeService.java
server/src/main/java/challenge/server/habit/controller/HabitController.java
server/src/main/java/challenge/server/habit/repository/HabitCustomRepository.java
server/src/main/java/challenge/server/habit/repository/HabitCustomRepositoryImpl.java
server/src/main/java/challenge/server/habit/repository/HabitRepository.java
server/src/main/java/challenge/server/habit/service/HabitService.java
server/src/main/java/challenge/server/report/repository/ReportCustomRepository.java
server/src/main/java/challenge/server/report/repository/ReportCustomRepositoryImpl.java
server/src/main/java/challenge/server/report/repository/ReportRepository.java
server/src/main/java/challenge/server/report/service/ReportService.java
server/src/main/java/challenge/server/review/repository/ReviewCustomRepository.java
server/src/main/java/challenge/server/review/repository/ReviewCustomRepositoryImpl.java
server/src/main/java/challenge/server/review/service/ReviewService.java
server/src/main/java/challenge/server/user/controller/UserController.java
server/src/main/java/challenge/server/user/service/UserService.java

feat - #191: no-offset pagination 구현

---

server/src/main/java/challenge/server/habit/controller/HabitController.java
server/src/main/java/challenge/server/habit/dto/HabitDto.java
server/src/main/java/challenge/server/habit/mapper/HabitMapperImpl.java
server/src/main/java/challenge/server/habit/statistics/AgeRatio.java
server/src/main/java/challenge/server/habit/statistics/SexRatio.java
server/src/main/java/challenge/server/habit/statistics/StatusRatio.java
server/src/main/resources/application-server.yml

fix: offset pageable 오류 수정

---

server/src/main/java/challenge/server/security/user/repository/EmailVerificationCustomRepositoryImpl.java

fix: QClass Compile 에러 해결

---

server/src/main/java/challenge/server/habit/dto/HabitDto.java
server/src/main/java/challenge/server/habit/entity/AgeRatio.java
server/src/main/java/challenge/server/habit/entity/Habit.java
server/src/main/java/challenge/server/habit/entity/SexRatio.java
server/src/main/java/challenge/server/habit/entity/StatusRatio.java
server/src/main/java/challenge/server/habit/mapper/HabitMapperImpl.java
server/src/main/java/challenge/server/security/user/repository/EmailVerificationCustomRepositoryImpl.java
server/src/main/resources/application-server.yml

feat: Habit 통계 데이터 기능 구현

---

server/src/main/java/challenge/server/habit/controller/HabitController.java
server/src/main/java/challenge/server/habit/dto/HabitDto.java
server/src/main/java/challenge/server/habit/entity/Habit.java
server/src/main/java/challenge/server/habit/mapper/HabitMapperImpl.java

- Habit DTO bodyHtml 필드명 수정
- failImgUrl optional 적용
Related to #30
어떤 변경 사항이 있나요?

fix - #30: bodyHTML 필드명 수정, fail 이미지 optional 적용

---

server/src/main/java/challenge/server/user/repository/EmailVerificationCustomRepositoryImpl.java

fix: compileQuerydsl 에러 해결

---

server/build.gradle
server/src/main/java/challenge/server/user/controller/UserController.java
server/src/main/java/challenge/server/user/service/UserService.java
server/src/main/resources/templates/hello.html

feat: 이메일 인증 완료 화면 추가

---

server/src/main/java/challenge/server/file/storage/AmazonS3ResourceStorage.java

fix: timeout 에러 해결

---

server/src/main/java/challenge/server/habit/entity/Habit.java

feat: habit body 타입 @lob 설정

---

client/components/header.tsx
client/pages/habit/detail/[habitId]/index.tsx

- Habit Detail UI 수정
Resolves: #363 
어떤 변경 사항이 있나요?

design - #363: Habit Detail UI 수정

---

server/src/main/java/challenge/server/ServerApplication.java

feat: 톰캣 서버 시간 변경(Asia/Seoul)

---

client/ducks/loginIdentitySlice.ts
client/module/authFunctionMoudules.ts
client/module/bookmarkFunctionMoudules.ts
client/module/challengeFunctionMoudules.ts
client/module/habitFunctionMoudules.ts
client/module/reportFunctionMoudules.ts
client/module/reviewFunctionModules.ts
client/module/userFunctionMoudules.ts
client/pages/habit/detail/[habitId]/index.tsx
client/pages/oauth.tsx

습관 시작 시 Detail Page UI 및 기능 수정
Resolves: #366 
어떤 변경 사항이 있나요?

feat - #366: 습관 시작 시 Detail Page UI 및 기능 수정

---

server/src/main/java/challenge/server/habit/dto/HabitDto.java
server/src/main/java/challenge/server/habit/entity/Habit.java
server/src/main/java/challenge/server/habit/mapper/HabitMapperImpl.java

- Habit 상세 DTO day 필드 추가
어떤 변경 사항이 있나요?

feat: Habit 상세 DTO day 필드 추가

---

server/build.gradle
server/src/main/java/challenge/server/commons/firebase/FCMService.java
server/src/main/java/challenge/server/commons/firebase/FCMTokenDao.java
server/src/main/java/challenge/server/commons/firebase/FCMinitializer.java
server/src/main/java/challenge/server/user/entity/User.java
server/src/main/java/challenge/server/user/service/UserService.java
server/src/main/resources/application-server.yml
server/src/main/resources/challenge-375405-firebase-adminsdk-ymetp-3cc2c2692f.json

feat: ddl-auto validate 설정

---

server/src/main/resources/application-server.yml

fix: ddl-auto create로 변경

---

server/src/main/java/challenge/server/challenge/repository/ChallengeCustomRepository.java
server/src/main/java/challenge/server/challenge/repository/ChallengeCustomRepositoryImpl.java
server/src/main/java/challenge/server/habit/dto/HabitDto.java
server/src/main/java/challenge/server/habit/mapper/HabitMapperImpl.java

- Habit 상세 DTO allChallengers 필드 추가
어떤 변경 사항이 있나요?

feat: Habit 상세 DTO allChallengers 필드 추가

---

client/pages/auth/index.tsx

Auth Page Base Height 조정
어떤 변경 사항이 있나요?

design - #382: Auth Page Base Height 조정

---

client/components/bottomNav/editHabitBottomNav.tsx
client/components/bottomNav/reviewHabitBottomNav.tsx
client/components/topNav.tsx
client/pages/auth/index.tsx
client/pages/habit/detail/[habitId]/index.tsx

Header, Nav z-index 수정
어떤 변경 사항이 있나요?

design - #382: Header, Nav z-index 수정

---

client/components/bottomNav/editHabitBottomNav.tsx
client/components/bottomNav/reviewHabitBottomNav.tsx
client/components/topNav.tsx
client/pages/auth/index.tsx
client/pages/habit/detail/[habitId]/index.tsx

style - #382: 오타 수정

---

client/components/bottomNav/editHabitBottomNav.tsx
client/components/bottomNav/reviewHabitBottomNav.tsx
client/components/topNav.tsx
client/pages/auth/index.tsx
client/pages/habit/detail/[habitId]/index.tsx
client/pages/habit/edit/[habitId].tsx

Habit Edit 예외처리 수정
어떤 변경 사항이 있나요?

fix - #382: Habit Edit 예외처리 수정

---

server/src/main/java/challenge/server/habit/controller/HabitController.java
server/src/main/java/challenge/server/habit/mapper/HabitMapperImpl.java
server/src/main/java/challenge/server/habit/service/HabitService.java
server/src/main/java/challenge/server/user/entity/User.java

- 습관 통계 LazyInitializationException 해결
어떤 변경 사항이 있나요?

fix: 습관 통계 LazyInitializationException 해결

---

server/src/main/java/challenge/server/challenge/controller/ChallengeController.java
server/src/main/java/challenge/server/challenge/service/ChallengeService.java

fix: 인증글 등록 시 LazyException 수정

---

client/components/bottomNav/editHabitBottomNav.tsx
client/components/bottomNav/reviewHabitBottomNav.tsx
client/components/topNav.tsx
client/pages/auth/index.tsx
client/pages/habit/detail/[habitId]/index.tsx
client/pages/habit/edit/[habitId].tsx
client/pages/habit/post.tsx

Habit Edit & Post 수정
어떤 변경 사항이 있나요?

fix - #382: Habit Edit & Post 수정

---

server/src/main/resources/application-server.yml

docs: yml fcm.certification 내용 정리

---

server/src/main/resources/application-server.yml

docs: fcm 비공개 키 파일 경로 추가

---

server/src/main/java/challenge/server/user/controller/UserController.java
server/src/main/java/challenge/server/user/entity/User.java
server/src/main/java/challenge/server/user/service/UserService.java

fix: FCM 푸쉬 알림 동의 여부 로직 삭제

---

server/src/main/java/challenge/server/firebase/FCMService.java
server/src/main/java/challenge/server/review/service/ReviewService.java
server/src/main/java/challenge/server/user/controller/UserController.java
server/src/main/java/challenge/server/user/service/UserService.java

feat: 알림 route 기능 구현

---

server/src/main/java/challenge/server/firebase/FCMService.java
server/src/main/java/challenge/server/firebase/Notice.java

feat: FCM data에 title, body, link 추가

---

server/src/main/java/challenge/server/firebase/FCMService.java
server/src/main/java/challenge/server/firebase/Notice.java
server/src/main/java/challenge/server/review/service/ReviewService.java

feat: FCM 푸쉬 알림 Title 수정
